channels:
  - pytorch
  - conda-forge
  - stanfordnlp
  - pypi
dependencies:
  - python==3.7.9
  - transformers==4.0.0
  - pytorch==1.7.0
  - stanza==1.1.1
  - python-dotenv==0.15.0
  - marshmallow==3.10.0
  - pip